version: '3.8'
services:
  fit_predict:
    build: .
    command: bash -c "python3 src/bikes_regression.py"
    image: 54367888/mle-template:latest
  tests:
    build: .
    command: bash -c "python3 -m pytest tests/test_model_quality.py"
