# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  rundocker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: run-my-docker-compose
        uses: isbang/compose-action@v0.1.1 
        with: 
         compose-file: 'docker-compose.yml'

  job_docker_compose:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "docker-compose.yml"
        up-flags: "--build"
        services: |
          vault
          db
          init_db
          kafka
          fit_predict
          tests
